filebeat.prospectors:
- type: docker
  containers.ids:
  - "*"
  processors:
    - add_kubernetes_metadata:
        api_server: ${K8S_APISERVER}
        namespace: ${K8S_NAMESPACE}
  fields_under_root: true
  fields:
    kubernetes:
      cluster:
        name: ${K8S_CLUSTER}
  reload.enabled: true

logging.level: ${FB_LOGLEVEL}

setup.template.name: "filebeat-${K8S_CLUSTER}"        #顶格，和output对其
setup.template.pattern: "filebeat-${K8S_CLUSTER}-*"   #顶格，和output对其
output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
  index: "filebeat-${K8S_CLUSTER}-%{+yyyy.MM.dd}"
