filebeat.prospectors:
- type: docker
  containers.ids:
  - "*"
  processors:
    - add_kubernetes_metadata:
        api_server: ${K8S_APISERVER}
        namespace: ${K8S_NAMESPACE}
  reload.enabled: true
logging.level: ${FB_LOGLEVEL}
output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
